### ISSUE TITLE
Improved /brand layout

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/design.ubuntu.com-design#2]
- Side nav to use accordion pattern ([see MAAS/dashboard theme](https://github.com/ubuntudesign/vanilla-dashboard-theme-design/tree/master/Accordion))
- Content area to display: Title, image below, description below (instead of image to the left of title/description)
- We will need updated images for each section that fit this new layout
- Sections are: The Ubuntu logo, The Canonical logo, Ubuntu partner logos, A vibrant palette, Our pictograms, Screenshots, Product photography, Charts and diagrams

**Comment by joanasa89** [comment]
Attached the proposal I've been working on. What are your thoughts on this? Any suggestions?
@yaili @spencerbygraves @kwm14 
![design ubuntu com brand](https://user-images.githubusercontent.com/21334617/26981335-b49fe50e-4d2c-11e7-96d1-34420ab573a0.jpg)

**Comment by kwm14** [comment]
@joanasa89 Looking good, but I have a couple of comments/suggestions:

- is there a reason why you have a large amount of white space between main nav and page title?
- I know that we use Ubuntu orange as our link colour, but perhaps we could make the secondary nav links #333 as it's quite overwhelming when you land on the page
- minor detail but on your paragraphs you've used 21px line height rather than our default 24px when using 16px font size
- thumbnails images looks good. Just an idea for 'Ubuntu logo' section, rather than using our orange on white logo I think you should replace it for our 'Alternative Ubuntu logo: black with orange roundel on white'. As this logo version should be used when less emphasis on Orange is needed, and as the page is quite 'orange heavy' it would make the brand logo stand out more

**Comment by spencerbygraves** [comment]
I'd echo @kwm14 comments. Also, I think we could find a better crop of a diagram, I like the way all the other boxes consistently have grey space around the image. The diagram seems the odd one out. Also, there seems to be slightly more space above the last two sections.

Looking good, thanks.

**Comment by joanasa89** [comment]
@kwm14 & @spencerbygraves Thank you for your feedback. See the most recent design.
Some points I will like to mention and have your opinions on:

- Colour links - You right, the orange is too overwhelming, but not sure if changing the colour of the links will be less intuitive. An underline 'hover state' will be enough?
- Left navigation - @frankiegranato I know we talked about this already but I still don't see a reason for using a different pattern when the other pages are using the "3rd navigation / breadcrumb style".  We probably should review this again, just to make everything consistent. 
- Charts and diagrams section - Do you think this image works better? Is hard to find a diagram that fits this space.

Let me know what do you think :)

![001 brand-assets page](https://user-images.githubusercontent.com/21334617/27139708-a20abb6a-511b-11e7-95c5-ce67dfd7f61c.jpg)

**Comment by spencerbygraves** [comment]
Yes, I think that diagram works better. Thanks

**Comment by kwm14** [comment]
Thanks @joanasa89 all updates you've made look great!
